# Generated by Django 3.2.9 on 2021-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='image',
            new_name='camera1',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='camera2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_status',
            field=models.CharField(max_length=100),
        ),
    ]
